# Generated by Django 5.0.9 on 2024-10-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paisapp_directory', '0002_type_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='Category',
            new_name='category',
        ),
    ]
