# Generated by Django 5.0.9 on 2024-10-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paisapp_directory', '0003_rename_category_type_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='Type',
            new_name='Tipo',
        ),
        migrations.RenameField(
            model_name='tipo',
            old_name='category',
            new_name='categoria',
        ),
    ]
